version: "2"
services:

  notification:
    image: openlmis/notification
    links:
      - log
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/notification-service:/var/log'
