version: "2"
services:

  notification:
    image: openlmis/dev
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env

volumes:
  gradlecache:
    external: false
