version: "2"
services:

  builder:
    image: openlmis/dev:3
    links:
      - log
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env

  sonar:
    image: openlmis/dev:3
    links:
      - log
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - 'clean'
      - 'sonarqube'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false $SONAR_LOGIN $SONAR_PASSWORD'
    env_file: .env

  image:
    build: .
    image: openlmis/notification

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/notification-service:/var/log'
