version: "2"
services:
  builder:
    image: openlmis/dev
    links:
      - db
      - log
      - auth
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env
  sonar:
    image: openlmis/dev
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - 'sonarqube'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false $SONAR_LOGIN $SONAR_PASSWORD'
    env_file: .env
  image:
    build: .
    image: openlmis/notification
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/notification-service:/var/log'
  auth:
    image: openlmis/auth
    env_file: .env
